@startuml

!include <C4/C4_Container>

title C4 level 2 - Voice chat app container diagram

System_Boundary(voiceChatApp, "Voice chat app container") {
    Container(networkModule, "Network", "Package", "Network module")
    Container(audioModule, "Audio", "Package", "Audio module")
    Container(uiModule, "UI", "Package", "User interface module")
}

System_Ext(javaxSound, "javax.sound", "Java sound library")
System_Ext(javaNet, "java.net", "Java network library")

@enduml