@startuml
!include <C4/C4_Component>

title C4 Level 3 - Voice chat app (components)

Container_Ext(vcaExt, "Voice chat app")
Person(user, "User")

Container_Boundary(vca, "Voice chat app") {
    Component(network, "Network", "Module", "Handles network operations")
    Component(audio, "Audio", "Module", "Captures and playbacks audio")
    Component(session, "Session", "Module", "Handles session. Stores addresses of all session members or the address of the host")
    Component(ui, "UI", "Module", "Handles user input")
    Component(orchestrator, "Orchestrator", "Module", "Orchestrates data flow depending on application mode (host/user). Aggregates audio if in host mode")
}

' app mode
Rel(user, ui, "Switches app mode")
Rel(user, ui, "Starts session")

' orchestration
Rel(ui, orchestrator, "Switches application mode")
Rel(ui, orchestrator, "Creates session")

Rel(orchestrator, session, "Creates session")
Rel(orchestrator, session, "Handles participants/host data")

BiRel(audio, orchestrator, "Transmits audio")
Rel(orchestrator, network, "Sends audio")
Rel(orchestrator, network, "Open tcp/udp connections")

' network
Rel(vcaExt, network, "Sends audio/tcp requests")
Rel(network, orchestrator, "Transmits audio/request")

@enduml