@startuml
!include <C4/C4_Component>

title C4 Level 3 - Voice chat app in HOST mode (components)

Container_Ext(vcaUser, "Voice chat app\n(user mode)")
Person(host, "Host")

Container_Boundary(vca, "Voice chat app\n(host mode)") {
    Component(network, "Network", "Module", "Network module")
    Component(audio, "Audio", "Module", "Audio module")
    Component(session, "Session", "Module", "Session module")
    Component(ui, "UI", "Module", "UI module")
}

Rel(vcaUser, network, "Sends audio/join request")
Rel(network, session, "Adds participant")
Rel(host, ui, "Starts/stops session")
Rel(ui, host, "Show participants data")
Rel(audio, network, "Transmits audio")
Rel(network, vcaUser, "Sends audio")
Rel(network, session, "Gets participants data")
Rel_L(ui, session, "Starts/stops session")
Rel(session, network, "Starts/stops udp/tcp server")

@enduml