@startuml
!include <C4/C4_Component>

title C4 Level 3 - Voice chat app in USER mode (components)

Container_Ext(vcaHost, "Voice chat app\n(host mode)")
Person(user, "User")

Container_Boundary(vca, "Voice chat app\n(host mode)") {
    Component(network, "Network", "Module", "Network module")
    Component(audio, "Audio", "Module", "Audio module")
    Component(session, "Session", "Module", "Session module")
    Component(ui, "UI", "Module", "UI module")
}

Rel(vcaHost, network, "Sends audio")
Rel(user, ui, "Starts/stops session")
Rel(audio, network, "Transmits audio")
Rel(network, vcaHost, "Sends audio/join request")
Rel(network, session, "Gets host data")
Rel_L(ui, session, "Starts/stops session")

@enduml